// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _3112847ac5cbe18418428da285a7c8f1_10240161870904192361 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray playerId;
            [FieldOffset(16)]
            public System.Byte isTracking;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _3112847ac5cbe18418428da285a7c8f1_10240161870904192361.playerIdMask;
            playerIdSimulationFrame = frame;
            FieldsMask |= _3112847ac5cbe18418428da285a7c8f1_10240161870904192361.isTrackingMask;
            isTrackingSimulationFrame = frame;
        }

        public static unsafe _3112847ac5cbe18418428da285a7c8f1_10240161870904192361 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 17) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 17) " +
                    "for component with ID 18");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 18");
            }

            var orig = new _3112847ac5cbe18418428da285a7c8f1_10240161870904192361();

            var comp = (Interop*)data;

            orig.playerId = comp->playerId.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->playerId.Data, (int)comp->playerId.Length) : null;
            orig.isTracking = comp->isTracking != 0;

            return orig;
        }


        public static uint playerIdMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame playerIdSimulationFrame;
        public System.String playerId;
        public static uint isTrackingMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame isTrackingSimulationFrame;
        public System.Boolean isTracking;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 18;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.playerIdSimulationFrame = other.playerIdSimulationFrame;
                this.playerId = other.playerId;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.isTrackingSimulationFrame = other.isTrackingSimulationFrame;
                this.isTracking = other.isTracking;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_3112847ac5cbe18418428da285a7c8f1_10240161870904192361 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.playerId;
                bitStream.WriteShortString(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.isTracking;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;

            return mask;
        }

        public static _3112847ac5cbe18418428da285a7c8f1_10240161870904192361 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new _3112847ac5cbe18418428da285a7c8f1_10240161870904192361();
            if (bitStream.ReadMask())
            {

                val.playerId = bitStream.ReadShortString();
                val.FieldsMask |= _3112847ac5cbe18418428da285a7c8f1_10240161870904192361.playerIdMask;
            }
            if (bitStream.ReadMask())
            {

                val.isTracking = bitStream.ReadBool();
                val.FieldsMask |= _3112847ac5cbe18418428da285a7c8f1_10240161870904192361.isTrackingMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_3112847ac5cbe18418428da285a7c8f1_10240161870904192361(" +
                $" playerId: { this.playerId }" +
                $" isTracking: { this.isTracking }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }

}
