// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.UInt32 ClientID;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525.ClientIDMask;
            ClientIDSimulationFrame = frame;
        }

        public static unsafe _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 4) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for component with ID 20");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 20");
            }

            var orig = new _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525();

            var comp = (Interop*)data;

            orig.ClientID = comp->ClientID;

            return orig;
        }


        public static uint ClientIDMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame ClientIDSimulationFrame;
        public System.UInt32 ClientID;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 20;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000001;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 1;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.UInt32 _ClientID_Min = 0;
        private static readonly System.UInt32 _ClientID_Max = 4294967295;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.ClientIDSimulationFrame = other.ClientIDSimulationFrame;
                this.ClientID = other.ClientID;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 1);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.ClientID, _ClientID_Min, _ClientID_Max, "_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525.ClientID", logger);
                data.ClientID = Coherence.Utils.Bounds.Clamp(data.ClientID, _ClientID_Min, _ClientID_Max);
                var fieldValue = data.ClientID;
                bitStream.WriteUIntegerRange(fieldValue, 32, 0);
            }
            mask >>= 1;

            return mask;
        }

        public static _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(1);
            }

            var val = new _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525();
            if (bitStream.ReadMask())
            {

                val.ClientID = bitStream.ReadUIntegerRange(32, 0);
                val.FieldsMask |= _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525.ClientIDMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525(" +
                $" ClientID: { this.ClientID }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(1, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(1, '0') })";
        }
    }

}
