// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_8ba6288ce78c7d545bd45c2c95156620_f57210664c5848e4840498b3c149dcdd : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_8ba6288ce78c7d545bd45c2c95156620_3ee6e8afb03741e9ab40b84738457919 : UIntBinding
    {   
        private global::Dissonance.Integrations.Coherence.CoherenceSyncVoice CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Dissonance.Integrations.Coherence.CoherenceSyncVoice)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525);
        public override string CoherenceComponentName => "_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.UInt32 Value
        {
            get { return (System.UInt32)(CastedUnityComponent.ClientID); }
            set { CastedUnityComponent.ClientID = (System.UInt32)(value); }
        }

        protected override (System.UInt32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525)coherenceComponent).ClientID;

            var simFrame = ((_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525)coherenceComponent).ClientIDSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_8ba6288ce78c7d545bd45c2c95156620_1473050850974972525)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ClientID = Value;
            }
            else
            {
                update.ClientID = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ClientIDSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _8ba6288ce78c7d545bd45c2c95156620_1473050850974972525();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_8ba6288ce78c7d545bd45c2c95156620 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_8ba6288ce78c7d545bd45c2c95156620>();
        
        private global::Dissonance.Integrations.Coherence.CoherenceSyncVoice _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d_CommandTarget;
        private global::Dissonance.Integrations.Coherence.CoherenceSyncVoice _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["f57210664c5848e4840498b3c149dcdd"] = new Binding_8ba6288ce78c7d545bd45c2c95156620_f57210664c5848e4840498b3c149dcdd(),
			["3ee6e8afb03741e9ab40b84738457919"] = new Binding_8ba6288ce78c7d545bd45c2c95156620_3ee6e8afb03741e9ab40b84738457919(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_8ba6288ce78c7d545bd45c2c95156620()
        {
            bakedCommandBindings.Add("a9e201ea5e5742e48ad0d35cc615ac0d", BakeCommandBinding__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d);
            bakedCommandBindings.Add("1703ec94090b4a54bf349e11d80656c6", BakeCommandBinding__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d_CommandTarget = (global::Dissonance.Integrations.Coherence.CoherenceSyncVoice)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Dissonance.Integrations.Coherence.CoherenceSyncVoice.ReceiveReliableDissonanceData",
            	"(System.Byte[]System.UInt32System.ByteSystem.ByteSystem.UInt32System.Int64)",
            	SendCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d,
            	ReceiveLocalCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d,
            	MessageTarget.All,
            	_8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataId = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataId = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(command);
        }

        private void ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(_8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d command)
        {
            var target = _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d_CommandTarget;
			target.ReceiveReliableDissonanceData((System.Byte[])(command.data),(System.UInt32)(command.dataId),(System.Byte)(command.index),(System.Byte)(command.total),(System.UInt32)(command.senderId),(System.Int64)(command.sendTime));
        }
        private void BakeCommandBinding__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6_CommandTarget = (global::Dissonance.Integrations.Coherence.CoherenceSyncVoice)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Dissonance.Integrations.Coherence.CoherenceSyncVoice.ReceiveUnreliableDissonanceData",
            	"(System.Byte[]System.UInt32System.ByteSystem.ByteSystem.UInt32System.Int64)",
            	SendCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6,
            	ReceiveLocalCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6,
            	MessageTarget.All,
            	_8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataId = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataId = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(command);
        }

        private void ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(_8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6 command)
        {
            var target = _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6_CommandTarget;
			target.ReceiveUnreliableDissonanceData((System.Byte[])(command.data),(System.UInt32)(command.dataId),(System.Byte)(command.index),(System.Byte)(command.total),(System.UInt32)(command.senderId),(System.Int64)(command.sendTime));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d castedCommand:
                    ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_a9e201ea5e5742e48ad0d35cc615ac0d(castedCommand);
                    break;
                case _8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6 castedCommand:
                    ReceiveCommand__8ba6288ce78c7d545bd45c2c95156620_1703ec94090b4a54bf349e11d80656c6(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_8ba6288ce78c7d545bd45c2c95156620 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_8ba6288ce78c7d545bd45c2c95156620>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
