// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_67eae9fd323863c44881b3e7a47edb1a_991280938c5a48258d0e6646c227e65e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_67eae9fd323863c44881b3e7a47edb1a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_67eae9fd323863c44881b3e7a47edb1a>();
        
        private global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521_CommandTarget;
        private global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657_CommandTarget;
        private global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["991280938c5a48258d0e6646c227e65e"] = new Binding_67eae9fd323863c44881b3e7a47edb1a_991280938c5a48258d0e6646c227e65e(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_67eae9fd323863c44881b3e7a47edb1a()
        {
            bakedCommandBindings.Add("6b939c3d989540f596ab35651a52c521", BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521);
            bakedCommandBindings.Add("5e6c62d7cb2a485583eeb8689aeb7657", BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657);
            bakedCommandBindings.Add("b8c9b31712ab46589dcd57ad91c205f6", BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521_CommandTarget = (global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Dissonance.Integrations.Coherence.CoherenceCommsNetwork.RestartComms",
            	"()",
            	SendCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521,
            	ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521,
            	MessageTarget.All,
            	_67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(command);
        }

        private void ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(_67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521 command)
        {
            var target = _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521_CommandTarget;
			target.RestartComms();
        }
        private void BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657_CommandTarget = (global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Dissonance.Integrations.Coherence.CoherenceCommsNetwork.ReceiveReliableDissonanceData",
            	"(System.Byte[]System.UInt32System.ByteSystem.ByteSystem.UInt32System.Int64)",
            	SendCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657,
            	ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657,
            	MessageTarget.All,
            	_67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataID = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataID = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(command);
        }

        private void ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(_67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657 command)
        {
            var target = _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657_CommandTarget;
			target.ReceiveReliableDissonanceData((System.Byte[])(command.data),(System.UInt32)(command.dataID),(System.Byte)(command.index),(System.Byte)(command.total),(System.UInt32)(command.senderId),(System.Int64)(command.sendTime));
        }
        private void BakeCommandBinding__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6_CommandTarget = (global::Dissonance.Integrations.Coherence.CoherenceCommsNetwork)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Dissonance.Integrations.Coherence.CoherenceCommsNetwork.ReceiveUnreliableDissonanceData",
            	"(System.Byte[]System.UInt32System.ByteSystem.ByteSystem.UInt32System.Int64)",
            	SendCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6,
            	ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6,
            	MessageTarget.All,
            	_67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataID = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(GenericCommandRequestArgs requestArgs)
        {
            var command = new _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.data = (System.Byte[])requestArgs.Args[0];
            command.dataID = (System.UInt32)requestArgs.Args[1];
            command.index = (System.Byte)requestArgs.Args[2];
            command.total = (System.Byte)requestArgs.Args[3];
            command.senderId = (System.UInt32)requestArgs.Args[4];
            command.sendTime = (System.Int64)requestArgs.Args[5];

            ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(command);
        }

        private void ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(_67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6 command)
        {
            var target = _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6_CommandTarget;
			target.ReceiveUnreliableDissonanceData((System.Byte[])(command.data),(System.UInt32)(command.dataID),(System.Byte)(command.index),(System.Byte)(command.total),(System.UInt32)(command.senderId),(System.Int64)(command.sendTime));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521 castedCommand:
                    ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_6b939c3d989540f596ab35651a52c521(castedCommand);
                    break;
                case _67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657 castedCommand:
                    ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_5e6c62d7cb2a485583eeb8689aeb7657(castedCommand);
                    break;
                case _67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6 castedCommand:
                    ReceiveCommand__67eae9fd323863c44881b3e7a47edb1a_b8c9b31712ab46589dcd57ad91c205f6(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_67eae9fd323863c44881b3e7a47edb1a Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_67eae9fd323863c44881b3e7a47edb1a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
