// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_3112847ac5cbe18418428da285a7c8f1_2bb19d189c1248a393d68714c9de456c : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_3112847ac5cbe18418428da285a7c8f1_c136c552263146ebb427a4d11968b183 : StringBinding
    {   
        private global::Dissonance.Integrations.Coherence.CoherencePlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Dissonance.Integrations.Coherence.CoherencePlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3112847ac5cbe18418428da285a7c8f1_10240161870904192361);
        public override string CoherenceComponentName => "_3112847ac5cbe18418428da285a7c8f1_10240161870904192361";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.playerId); }
            set { CastedUnityComponent.playerId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent).playerId;

            var simFrame = ((_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent).playerIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerId = Value;
            }
            else
            {
                update.playerId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3112847ac5cbe18418428da285a7c8f1_10240161870904192361();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_3112847ac5cbe18418428da285a7c8f1_51bddffc98d141c98e0713ce9e123ae3 : BoolBinding
    {   
        private global::Dissonance.Integrations.Coherence.CoherencePlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Dissonance.Integrations.Coherence.CoherencePlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3112847ac5cbe18418428da285a7c8f1_10240161870904192361);
        public override string CoherenceComponentName => "_3112847ac5cbe18418428da285a7c8f1_10240161870904192361";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isTracking); }
            set { CastedUnityComponent.isTracking = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent).isTracking;

            var simFrame = ((_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent).isTrackingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3112847ac5cbe18418428da285a7c8f1_10240161870904192361)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isTracking = Value;
            }
            else
            {
                update.isTracking = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isTrackingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3112847ac5cbe18418428da285a7c8f1_10240161870904192361();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_3112847ac5cbe18418428da285a7c8f1 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_3112847ac5cbe18418428da285a7c8f1>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["2bb19d189c1248a393d68714c9de456c"] = new Binding_3112847ac5cbe18418428da285a7c8f1_2bb19d189c1248a393d68714c9de456c(),
			["c136c552263146ebb427a4d11968b183"] = new Binding_3112847ac5cbe18418428da285a7c8f1_c136c552263146ebb427a4d11968b183(),
			["51bddffc98d141c98e0713ce9e123ae3"] = new Binding_3112847ac5cbe18418428da285a7c8f1_51bddffc98d141c98e0713ce9e123ae3(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_3112847ac5cbe18418428da285a7c8f1()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_3112847ac5cbe18418428da285a7c8f1 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_3112847ac5cbe18418428da285a7c8f1>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
